---

  # [en_US] Time intervals configuration
  #
  # [pt_BR] Configurações de intervalos de tempo
  #
  time_intervals:
    send_common_heroes_for_work: 5

    send_heroes_for_work: 15
    
    refresh_heroes_positions: 5
    
    check_for_new_map_button: 5
    
    check_for_captcha: 1

    check_for_login: 5

    interval_between_moviments: 0.01

  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    common: 0.7

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    green_bar: 0.9

  home:
    enable: False
    # If bot is sending the wrong hero home, make this number bigger.
    # if bot is not sending any hero home make this number smaller.
    hero_threshold: 0.8
    home_button_threshold: 0.9


  # [en_US]
  # Default value: 60
  #
  # [pt_BR]
  # Valor padrão: 60
  scroll_size: 60

# [en_US]
  # Default value: 3
  #
  # [pt_BR]
  # Valor padrão: 3
  scroll_attemps: 5

  # [en_US]
  # Default value: true
  #
  # [pt_BR]
  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # [en_US]
  # Default value: 200
  #
  # [pt_BR]
  # Valor padrão: 200
  click_and_drag_amount: 200

  # [en_US]
  # Default value: green
  # Available options:
  # all   = select all heroes (regardless of the stamina bar)
  # green = select the heroes with green stamina bar (half or full)
  # full  = select only the heroes with full stamina bar
  #
  # [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "green"

  # [en_US] Option for save logs to a file (logs.txt)
  # Default value: False
  # Available options: False or True
  #
  # [pt_BR] Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão : False
  # Opções disponíveis: False ou True
  save_log_to_file: False
