stat = [[
      "Point:1; Monster:1; ClickCount:0; KillTime:6; isBoss:false",
      "Point:1; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:2; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:2; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:3; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:3; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:4; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:4; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:5; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:5; Monster:2; ClickCount:0; KillTime:2; isBoss:false",

      "Point:6; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:6; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:7; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:7; Monster:2; ClickCount:0; KillTime:2; isBoss:false",

      "Point:8; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:8; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:9; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:9; Monster:2; ClickCount:0; KillTime:10; isBoss:false",

      "Point:10; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:10; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:11; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:11; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:12; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:12; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:13; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:13; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:14; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:14; Monster:2; ClickCount:0; KillTime:1; isBoss:false",

      "Point:15; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:15; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:16; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:16; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:17; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:17; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:18; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:18; Monster:2; ClickCount:0; KillTime:0; isBoss:false",

      "Point:19; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:19; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:19; Monster:3; ClickCount:0; KillTime:1; isBoss:false",

      "Point:20; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:20; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:20; Monster:3; ClickCount:0; KillTime:0; isBoss:false",

      "Point:21; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:21; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:21; Monster:3; ClickCount:0; KillTime:0; isBoss:false",

      "Point:22; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:22; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:22; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:23; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:23; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:23; Monster:3; ClickCount:0; KillTime:1; isBoss:false",
      "Point:24; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:24; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:24; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:25; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:25; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:25; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:25; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:26; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:26; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:26; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:26; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:26; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:27; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:27; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:27; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:27; Monster:4; ClickCount:0; KillTime:2; isBoss:false",
      "Point:27; Monster:5; ClickCount:0; KillTime:1; isBoss:false",
      "Point:27; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:28; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:28; Monster:8; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:29; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:8; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:9; ClickCount:0; KillTime:0; isBoss:false",
      "Point:29; Monster:10; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:30; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:8; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:9; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:10; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:11; ClickCount:0; KillTime:0; isBoss:false",
      "Point:30; Monster:12; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:31; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:8; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:9; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:10; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:11; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:12; ClickCount:0; KillTime:0; isBoss:false",
      "Point:31; Monster:13; ClickCount:0; KillTime:1; isBoss:false",
      "Point:31; Monster:14; ClickCount:0; KillTime:0; isBoss:false",
      "Point:32; Monster:0; ClickCount:0; KillTime:5; isBoss:true",
      "Skill Id: 23 Arms lore",
      "Skill Id: 24 Fencing",
      "Skill Id: 25 Critical strike",
      "Skill Id: 26 Perfect Vessel",
      "Skill Id: 27 Harmony",
      "Skill Id: 21 Accumulation",
      "Skill Id: 19 Electric charge",
      "Skill Id: 20 Lightning burst",
      "Skill Id: 22 Ionization",
      "Skill Id: 11 Open Wounds",
      "Skill Id: 13 Wildfire",
      "Skill Id: 12 Sucker Punch",
      "Skill Id: 7 Acid Burn",
      "Skill Id: 1 Combo",
      "Skill Id: 1 Combo",
      "Skill Id: 15 Tranquility",
      "Skill Id: 17 Soul prism",
      "Skill Id: 16 Enchanted Weapon",
      "Skill Id: 18 Inner Fire",
      "Skill Id: 10 Elemental disbalance",
      "Skill Id: 8 Flesh Erosion",
      "Skill Id: 9 Cold Rush",
      "Skill Id: 14 Vampirism",
      "Skill Id: 2 Crippling Strike",
      "Skill Id: 3 Weakness",
      "Skill Id: 4 Battle trance",
      "Skill Id: 5 Vulnerability",
      "Skill Id: 23 Arms lore"
   ],
   [
      "Point:1; Monster:1; ClickCount:0; KillTime:63; isBoss:false",
      "Point:1; Monster:2; ClickCount:0; KillTime:12; isBoss:false",

      "Point:2; Monster:1; ClickCount:0; KillTime:314; isBoss:false",
      "Point:2; Monster:2; ClickCount:0; KillTime:310; isBoss:false",

      "Point:3; Monster:1; ClickCount:0; KillTime:416; isBoss:false",
      "Point:3; Monster:2; ClickCount:0; KillTime:412; isBoss:false",

      "Point:4; Monster:1; ClickCount:0; KillTime:521; isBoss:false",
      "Point:4; Monster:2; ClickCount:0; KillTime:515; isBoss:false",
      "Point:4; Monster:3; ClickCount:0; KillTime:565; isBoss:false",

      "Point:5; Monster:1; ClickCount:0; KillTime:553; isBoss:false",
      "Point:5; Monster:2; ClickCount:0; KillTime:669; isBoss:false",
      "Point:5; Monster:3; ClickCount:0; KillTime:669; isBoss:false",

      "Point:6; Monster:1; ClickCount:0; KillTime:92; isBoss:false",
      "Point:6; Monster:2; ClickCount:0; KillTime:4; isBoss:false",
      "Point:6; Monster:3; ClickCount:0; KillTime:0; isBoss:false",

      "Point:7; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:7; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:7; Monster:3; ClickCount:0; KillTime:0; isBoss:false",

      "Point:8; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:8; Monster:2; ClickCount:0; KillTime:2; isBoss:false",
      "Point:8; Monster:3; ClickCount:0; KillTime:0; isBoss:false",

      "Point:9; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:9; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:9; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      
      "Point:10; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:10; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:10; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:10; Monster:4; ClickCount:0; KillTime:0; isBoss:false",

      "Point:11; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:11; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:11; Monster:3; ClickCount:0; KillTime:2; isBoss:false",
      "Point:11; Monster:4; ClickCount:0; KillTime:0; isBoss:false",

      "Point:12; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:12; Monster:2; ClickCount:0; KillTime:1; isBoss:false",
      "Point:12; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:12; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:12; Monster:5; ClickCount:0; KillTime:0; isBoss:false",

      "Point:13; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:13; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:13; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:13; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:13; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:13; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:13; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      
      "Point:14; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:14; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:14; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:14; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:14; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:14; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:14; Monster:7; ClickCount:0; KillTime:0; isBoss:false",

      "Point:15; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:15; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:15; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:15; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:15; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:15; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:15; Monster:7; ClickCount:0; KillTime:0; isBoss:false",

      "Point:16; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:16; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:4; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:5; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:6; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:16; Monster:8; ClickCount:0; KillTime:0; isBoss:false",

      "Point:17; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:17; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:17; Monster:3; ClickCount:0; KillTime:0; isBoss:false",
      "Point:17; Monster:4; ClickCount:0; KillTime:1; isBoss:false",
      "Point:17; Monster:5; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:6; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:17; Monster:8; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:9; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:10; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:11; ClickCount:0; KillTime:2; isBoss:false",
      "Point:17; Monster:12; ClickCount:0; KillTime:0; isBoss:false",
      "Point:17; Monster:13; ClickCount:0; KillTime:73; isBoss:false",

      "Point:18; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:18; Monster:2; ClickCount:0; KillTime:0; isBoss:false",
      "Point:18; Monster:3; ClickCount:0; KillTime:1; isBoss:false",
      "Point:18; Monster:4; ClickCount:0; KillTime:1; isBoss:false",
      "Point:18; Monster:5; ClickCount:0; KillTime:2; isBoss:false",
      "Point:18; Monster:6; ClickCount:0; KillTime:2; isBoss:false",
      "Point:18; Monster:7; ClickCount:0; KillTime:0; isBoss:false",
      "Point:18; Monster:8; ClickCount:0; KillTime:1; isBoss:false",
      "Point:18; Monster:9; ClickCount:0; KillTime:1; isBoss:false",
      "Point:18; Monster:10; ClickCount:0; KillTime:9; isBoss:false",
      "Point:18; Monster:11; ClickCount:0; KillTime:0; isBoss:false",
      "Point:18; Monster:12; ClickCount:0; KillTime:0; isBoss:false",
      "Point:18; Monster:13; ClickCount:0; KillTime:0; isBoss:false",
      "Point:18; Monster:14; ClickCount:0; KillTime:1; isBoss:false",

      "Point:19; Monster:1; ClickCount:0; KillTime:5; isBoss:false",
      "Point:19; Monster:2; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:3; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:4; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:5; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:6; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:7; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:8; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:9; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:10; ClickCount:0; KillTime:0; isBoss:false",
      "Point:19; Monster:11; ClickCount:0; KillTime:2; isBoss:false",
      "Point:19; Monster:12; ClickCount:0; KillTime:0; isBoss:false",
      "Point:19; Monster:13; ClickCount:0; KillTime:0; isBoss:false",
      "Point:19; Monster:14; ClickCount:0; KillTime:0; isBoss:false",
      "Point:19; Monster:15; ClickCount:0; KillTime:0; isBoss:false",
      
      "Point:20; Monster:0; ClickCount:0; KillTime:5; isBoss:true",
      "Skill Id: 1 Combo",
      "Skill Id: 2 Crippling Strike",
      "Skill Id: 3 Weakness",
      "Skill Id: 4 Battle trance",
      "Skill Id: 5 Vulnerability",
      "Skill Id: 10 Elemental disbalance",
      "Skill Id: 9 Cold Rush",
      "Skill Id: 6 Flaming Blade",
      "Skill Id: 7 Acid Burn",
      "Skill Id: 8 Flesh Erosion",
      "Skill Id: 11 Open Wounds",
      "Skill Id: 12 Sucker Punch",
      "Skill Id: 13 Wildfire",
      "Skill Id: 14 Vampirism",
      "Skill Id: 15 Tranquility",
      "Skill Id: 17 Soul prism",
      "Skill Id: 16 Enchanted Weapon",
      "Skill Id: 18 Inner Fire",
      "Skill Id: 21 Accumulation",
      "Skill Id: 22 Ionization",
      "Skill Id: 23 Arms lore",
      "Skill Id: 24 Fencing",
      "Skill Id: 25 Critical strike",
      "Skill Id: 26 Perfect Vessel",
      "Skill Id: 27 Harmony",
      "Skill Id: 19 Electric charge",
      "Skill Id: 20 Lightning burst"
   ]]